version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 "NOTICE",
 "REUSE.toml"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

# seedrng has lots of license options. Pick MIT.
[[annotations]]
path = [
 "src/seedrng.c"
]
precedence = "override"
SPDX-FileCopyrightText = "2022 Jason A. Donenfeld <Jason@zx2c4.com>"
SPDX-License-Identifier = "MIT"
